clear
close all

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Ralph S-J\Documents\GitHub\solar-cell-profiling\data\solar-cell-profile-data.xlsx
%    Worksheet: 50x60
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/16 15:59:09

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Ralph S-J\Documents\GitHub\solar-cell-profiling\data\solar-cell-profile-data.xlsx','50x60','A4:C83');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
light = data(:,1);
current = data(:,2);
voltage = data(:,3);

%% Clear temporary variables
clearvars data raw;

%% CALCULATE

Power = (current .* voltage)/1e6;
Impedance = voltage ./ current;

% time
figure
subplot(2,2,1)
plot(current);
ylabel('Current (mA)')

subplot(2,2,2)
plot(voltage);
ylabel('Voltage (mA)')

subplot(2,2,3)
plot(Impedance);
ylabel('Impedance (\Omega)')

subplot(2,2,4)
plot(light);
ylabel('Light (lux)')


% light
figure
subplot(3,1,1)
plot(light,current, '.')
xlabel('Light (lux)');
ylabel('Current (mA)')

subplot(3,1,2)
plot(light,voltage, '.')
xlabel('Light (lux)');
ylabel('Voltage (mA)')

subplot(3,1,3)
plot(light,Impedance, '.')
xlabel('Light (lux)');
ylabel('Impedance (\Omega)')


figure
plot(light, Power, '.')
xlabel('Light (lux)');
ylabel('Power (W)')